API/urls.py
from django.urls import path
from API.views import *

app_name = 'API'

urlpatterns = [
    path('<id>/', api_detail_category_view, name='category_detail'),
    path('', api_all_category_view, name='category'),
    # path('delete/<id>/', api_delete_category_view, name='category_delete'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop import views
from users.views import register
import django.contrib.auth.urls as accounts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('', views.IndexArticle.as_view(), name='index'),
    path('register/', register, name='register'),
    path('', include(accounts)),

    # REST API
    path('shop-api/', include('API.urls', 'API'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'товар'
        verbose_name_plural = 'товары'


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])


class Article(models.Model):

    name = models.CharField(max_length=70, verbose_name='Заголовок статьи')
    text = models.CharField(max_length=1000, verbose_name='Текст статьи')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создана')
    image = models.ImageField(
        upload_to='articles/',
        blank=True,
        verbose_name='Изображение'
    )
    products = models.ManyToManyField(
        Product,
        related_name='products'
    )

    class Meta:
        ordering = ('created',)
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from cart.forms import CartAddProductForm
from .models import Category, Product, Article


class IndexArticle(ListView):
    template_name = 'shop/index.html'
    model = Article
    ordering = 'created'


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">ЧЕТВЁ₽ОЧКА</a>
      <form action="/shop/">
        <input type="submit" value="Каталог товаров" />
      </form>
      {% if not user.is_authenticated %}
      <form action="/login/">
        <input type="submit" value="LOGIN" />
      </form>
      {% else %}
      <form action="/logout/">
        <input type="submit" value="LOGOUT" />
      </form>
      {% endif %}
    </div>
    <div id="subheader">
      <div class="cart">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            Ваша корзина:
            <a href="{% url "cart:cart_detail" %}">
              Всего товаров: {{ total_items }}
              на сумму {{ cart.get_total_price }}₽
            </a>
          {% else %}
            Ваша корзина пуста.
          {% endif %}
        {% endwith %}
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}


{% for article in article_list %}
  <div align="center">
  <h2>{{article.name}}</h2> <br>
  <h4>{{ article.text }}</h4><br>
  <img src="{% if article.image %} {{ article.image.url }}
  {% else %} {% static 'img/no_image.png' %} {% endif %}" width="500"> <br>

    {% for product in article.products.all %}
    <a href="{{product.get_absolute_url}}"> <h3>{{product.name}} . . . {{ product.price }} ₽ </h3> </a>
    {% endfor %}
  </div>

{% endfor %}
{% endblock %}